name: meal_app_planner
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc:
  path_provider:
  path:
  flutter_svg:
  image_picker:
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  cupertino_icons: ^1.0.8
  firebase_auth_web: ^5.8.13
  js: ^0.7.2
  http: ^1.4.0
  shared_preferences: ^2.2.2
  intl:
  hive:
  hive_flutter:
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons:
  hive_generator:
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/meals/
    - assets/filters/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600